## this is ci yaml file just for the testing 

name : CI Pipeline 

on: 
  push:
   branches:
     - "main"

jobs:
 build:
  runs-on: ubuntu-latest


  steps:
    - uses: actions/checkout@v3
    - uses: iterative/setup-cml@v2
    - uses: actions/setup-python
      with:
       python-version: 3.11

    - name: install dependencies

      run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt


    - name: run main_file
      run: |
       python main.py

    - name: create cml report 

      env:
       REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}  
      run: |
         echo "# first line of our report">>report.md
         echo "## Bar plots" >> >report.md
         echo '![](./bars.png "Bar plot")'>> report.md  
         echo "## line plots">>report.md
         echo '![](./lines.png  "lines plot ")'>> report.md

         cml comment create report.md